### ISSUE TITLE
Support incomplete AST

### ISSUE THREAD

**Issue by nzt** [textlint/textlint-util-to-string#13]
Hello, I'm author of `textlint-plugin-latex2e`.
We are trying to use parser `latex-utensils` in internals for the efficiency. 
latex-utensils parses document as an AST which is ommitted any white-spaces.

For example, the following source code parses as

```tex
\begin{document}I  has a pens\end{document}
```
<details>
    <summary>1. Result of latex-utensils</summary>

      {                     
        "kind": "ast.root", 
        "content": [        
          {                   
            "kind": "env",  
            "name": "document", 
            "args": [],     
            "content": [    
              {             
                "kind": "text.string", 
                "content": "I",                                      
                "location": { 
                  "start": {         
                    "offset": 16, 
                    "line": 1, 
                    "column": 17 
                  },                     
                  "end": {  
                    "offset": 17, 
                    "line": 1, 
                    "column": 18                                                  
                  }                                                                                                       
                }                                                                                                         
              },                                                                                                          
              {                                                                                                           
                "kind": "text.string",                                                                                    
                "content": "has",                                                                                         
                "location": {                                                                                             
                  "start": {                                                                                              
                    "offset": 19,                                                                                         
                    "line": 1,                                                                                            
                    "column": 20                                                                                          
                  },                                                                                                      
                  "end": {                                                                                                
                    "offset": 22,                                                                                         
                    "line": 1,                                                                                            
                    "column": 23                                                                                          
                  }                                                                                                       
                }                                                                                                         
              },                                                                                                          
              {                                                                                                           
                "kind": "text.string",                                                                                    
                "content": "a",                                                                                           
                "location": {                                                                                             
                  "start": {                                                                                              
                    "offset": 24,                                                                                         
                    "line": 1,                                                                                            
                    "column": 25                                                                                          
                  },                                                                                                      
                  "end": {                                                                                                
                    "offset": 25,                                                                                         
                    "line": 1,                                                                                            
                    "column": 26                                                                                          
                  }                                                                                                       
                }                                                                                                         
              },                                                                                                          
              {                                                                                                           
                "kind": "text.string",                                                                                    
                "content": "pens",                                                                                        
                "location": {                                                                                             
                  "start": {                                                                                              
                    "offset": 27,                                                                                         
                    "line": 1,                                                                                            
                    "column": 28                                                                                          
                  },                                                                                                      
                  "end": {                                                                                                
                    "offset": 31,                                                                                         
                    "line": 1,                                                                                            
                    "column": 32                                                                                          
                  }                                                                                                       
                }                                                                                                         
              }                                                                                                           
            ],                                                                                                            
            "location": {                                                                                                 
              "start": {                                                                                                  
                "offset": 0,                                                                                              
                "line": 1,                                                                                                
                "column": 1                                                                                               
              },                                                                                                          
              "end": {                                                                                                    
                "offset": 45,                                                                                             
                "line": 1,                                                                                                
                "column": 46                                                                                              
              }                                                                                                           
            }                                                                                                             
          }                                                                                                               
        ]                                                                                                                 
      }                          
</details>
<details>
    <summary>2. Result of textlint-plugin-latex2e (unpublished version)</summary>

      { 
        "kind": "ast.root",
        "content": [
          {
            "kind": "env",
            "name": "document",
            "args": [],
            "content": [
              {
                "kind": "text.string",
                "content": "I",
                "location": {
                  "start": {
                    "offset": 16,
                    "line": 1,
                    "column": 17
                  },
                  "end": {
                    "offset": 17,
                    "line": 1,
                    "column": 18
                  }
                }
              },
              {
                "kind": "text.string",
                "content": "has",
                "location": {
                  "start": {
                    "offset": 19,
                    "line": 1,
                    "column": 20
                  },
                  "end": {
                    "offset": 22,
                    "line": 1,
                    "column": 23
                  }
                }
              },
              {
                "kind": "text.string",
                "content": "a",
                "location": {
                  "start": {
                    "offset": 24,
                    "line": 1,
                    "column": 25
                  },
                  "end": {
                    "offset": 25,
                    "line": 1,
                    "column": 26
                  }
                }
              },
              {
                "kind": "text.string",
                "content": "pens",
                "location": {
                  "start": {
                    "offset": 27,
                    "line": 1,
                    "column": 28
                  },
                  "end": {
                    "offset": 31,
                    "line": 1,
                    "column": 32
                  }
                }
              }
            ],
            "location": {
              "start": {
                "offset": 0,
                "line": 1,
                "column": 1
              },
              "end": {
                "offset": 45,
                "line": 1,
                "column": 46
              }
            }
          }
        ]
      }
</details>

<details>
    <summary>3. Content of StringSource</summary>

    {
      "rootNode": {
        "loc": {
          "start": {
            "line": 1,
            "column": 0
          },
          "end": {
            "line": 1,
            "column": 42
          }
        },
        "range": [
          0,
          42
        ],
        "raw": "\\begin{document}I has a pens\\end{document}",
        "type": "Paragraph",
        "children": [
          {
            "loc": {
              "start": {
                "line": 1,
                "column": 16
              },
              "end": {
                "line": 1,
                "column": 17
              }
            },
            "range": [
              16,
              17
            ],
            "raw": "I",
            "type": "Str",
            "value": "I"
          },
          {
            "loc": {
              "start": {
                "line": 1,
                "column": 18
              },
              "end": {
                "line": 1,
                "column": 21
              }
            },
            "range": [
              18,
              21
            ],
            "raw": "has",
            "type": "Str",
            "value": "has"
          },
          {
            "loc": {
              "start": {
                "line": 1,
                "column": 22
              },
              "end": {
                "line": 1,
                "column": 23
              }
            },
            "range": [
              22,
              23
            ],
            "raw": "a",
            "type": "Str",
            "value": "a"
          },
          {
            "loc": {
              "start": {
                "line": 1,
                "column": 24
              },
              "end": {
                "line": 1,
                "column": 28
              }
            },
            "range": [
              24,
              28
            ],
            "raw": "pens",
            "type": "Str",
            "value": "pens"
          }
        ]
      },
      "tokenMaps": [
        {
          "original": [
            16,
            17
          ],
          "intermediate": [
            16,
            17
          ],
          "value": "I",
          "generated": [
            0,
            1
          ]
        },
        {
          "original": [
            18,
            21
          ],
          "intermediate": [
            18,
            21
          ],
          "value": "has",
          "generated": [
            1,
            4
          ]
        },
        {
          "original": [
            22,
            23
          ],
          "intermediate": [
            22,
            23
          ],
          "value": "a",
          "generated": [
            4,
            5
          ]
        },
        {
          "original": [
            24,
            28
          ],
          "intermediate": [
            24,
            28
          ],
          "value": "pens",
          "generated": [
            5,
            9
          ]
        }
      ],
      "generatedString": "Ihasapens",
      "originalSource": {
        "indice": [
          0
        ]
      },
      "generatedSource": {
        "indice": [
          0
        ]
      }
    }
</details>

There are `generatedString: "Ihasapens"` in 3. Thus, SourceString class did not append any whitespaces even if the `end` of `loc` is different from the `start` of `loc` in the previous node.
I mean, I propose that StringSource adds whitespace when there are gap  between two nodes (such as `I` and `has` in 2) to fill the gap.
Concisely,  current behavior of this library is similar to `["I", "has", "a", "pens"].join()` and I expect `["I", "has", "a", "pens"].join(" ")`.

**Comment by azu** [comment]
Current implementation is that just join `node.value`s.

https://github.com/textlint/textlint-util-to-string/blob/93f26d96a704244d7d06ab3a029095a2fdeff3ae/src/StringSource.ts#L275

I think that two approach exists

- textlint-util-to-string check `node`'s location before join `node.value`
  - This issue is suggested

```js
        // pasudo code
        const DEFAULT_SPACE = " "
        const padding = tokenMap.original.start  - prevTokenMap.original.end;
        if(isLastTokenMap(tokenMap)){
             const endPadding = rootNode.original.end  - tokenMap.original.end 
             this.generatedString += DEFAULT_SPACE.repeat(padding) + tokenMap.generatedValue + "DEFAULT_SPACE.repeat(padding)
        } else {
             this.generatedString += DEFAULT_SPACE.repeat(padding) + tokenMap.generatedValue;
        }
```

- Modify AST before using textlint-util-to-string
  - Add white space node(Str?) to missing range
  
Both approach is valid, I think.
