### ISSUE TITLE
originalPositionFromIndex is broken?

### ISSUE THREAD

**Issue by nodaguti** [textlint/textlint-util-to-string#4]
Hello,

I'm now updating `textlint-rule-ginger`'s dependencies and when I updated `textlint-util-to-string` from v1.2.0 to v2.0.1, its tests started to fail.

## Steps to reproduce
nodaguti/textlint-rule-ginger#65

If you clone the above branch and run `npm install textlint-util-to-string@1.2.0`, the problem will cease.

## Possible solutions
I've implanted `console.log` after `originalPositionFromIndex` ([code](https://github.com/nodaguti/textlint-rule-ginger/blob/7e98100b1ea5ce9f4348fa5ef40f9848c0f92ba8/src/ginger.js#L67)), and found that `originalPositionFromIndex` reported `NaN` as a `column` for Markdown texts (See [this Travis results](https://travis-ci.org/nodaguti/textlint-rule-ginger/jobs/196267182)).

Strangely, even though I manually reverted the changes within StringSource.js between v1.2.0 and v2.0.1, the problem still occurred, so I couldn't narrow the causes.

Am I doing something wrong? Any suggestions?

Thank you.

**Comment by azu** [comment]
Thanks for report!
I've fix it and release https://github.com/textlint/textlint-util-to-string/releases/tag/2.0.2

@nodaguti Can you confirm it?

**Comment by nodaguti** [comment]
Thank you so much for the quick work, I've confirmed this issue has been resolved.
